---
- hosts: all
  become: yes
  tasks:
    - name: Log in to DockerHub with token
      docker_login:
        username: "{{ lookup('env', 'DOCKERHUB_USERNAME') }}"
        password: "{{ lookup('env', 'DOCKERHUB_TOKEN') }}"