---
  - name: Wat for target connection to become reachable
    wait_for_connection:

  - name: gather_facts from machines
    hosts: all
    gather_facts: true

  - name: Run playbook for debianlike machines
    import_playbook: apt-update.yml
    when: ansible_distribution == 'Ubuntu'

  - name: Run playbook for debianlike machines
    import_playbook: apt-install-services.yml
    when: ansible_distribution == 'Ubuntu'
