---
  - name: Wait for target connection to become reachable
    hosts: all
    gather_facts: no
    tasks:
        - name: Wait 300 seconds for target connection
          ansible.builtin.wait_for_connection:
            delay: 60
            timeout: 300

  - name: gather_facts from machines
    hosts: all
    gather_facts: true

  - name: Run playbook for debianlike machines
    import_playbook: apt-update.yml
    when: ansible_distribution == 'Ubuntu'

  - name: Run playbook for debianlike machines
    import_playbook: apt-install-services.yml
    when: ansible_distribution == 'Ubuntu'
